[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
check_untyped_defs = True
ignore_missing_imports = True
exclude = (?x)(
    __pycache__
    | \.git
    | \.venv
  )

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-shared.storage.*]
ignore_errors = False

[mypy-shared.models.*]
disallow_untyped_defs = True
